pull_request_rules:
  - name: Automatic merge when CI passes and fedor-infra/data-team reviews
    conditions:
      - check-success=Run tests
      - approved-reviews-by=@fedora-infra/data-team
    actions:
      merge:
        method: merge