pull_request_rules:
  - name: Automatic merge when CI passes and fedor-infra/data-team reviews
    conditions:
      - approved-reviews-by=@fedora-infra/data-team
      - check-success=Checks
      - check-success=Licenses
      - check-success=Licenses(consumer)
      - check-success=Licenses(commands)
      - check-success=Unit tests(3.7, models)
      - check-success=Unit tests(3.7, consumer)
      - check-success=Unit tests(3.7, commands)
      - check-success=Unit tests(3.8, models)
      - check-success=Unit tests(3.8, consumer)
      - check-success=Unit tests(3.8, commands)
      - check-success=Unit tests(3.9, models)
      - check-success=Unit tests(3.9, consumer)
      - check-success=Unit tests(3.9, commands)
    actions:
      merge:
        method: merge
